apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: homepage
data:
  services.yaml: |
    - Platform:
        - Argo CD:
            href: https://argocd.nerv.local
            description: GitOps dashboard
            icon: argo-cd.png
        - Who Am I:
            href: https://whoami.nerv.local
            description: Who Am I
            icon: nginx.png
        - Quote API:
            href: https://quote.nerv.local
            description: Random NERV quote service
            icon: mdi-format-quote-close
            widget:
              type: customapi
              url: http://quote-api.homepage.svc.cluster.local/quote
              method: GET
              mappings:
                - field: text
                  label: Quote
                - field: source
                  label: Source
    - Observability:
        - Grafana:
            href: https://grafana.nerv.local
            description: Cluster dashboards
            icon: grafana.png
    - Coming Soon:
        - Jellyfin:
            description: Media server
            icon: jellyfin.png
        - Photo of the Day: 
            description: Personal project
            icon: camera.png

  bookmarks.yaml: |
    - Homelab:
        - GitHub Repo:
            - abbr: GH
              href: https://github.com/staticparsley/homelab-nerv
        - RubenMarin.dev:
            - abbr: DEV 
              href: https://rubenmarin.dev
        - RMarinPhoto:
            - abbr: PHOTO 
              href: https://rmarinphoto.com

  settings.yaml: |
    title: Nerv
    theme: dark
    color: slate
    headerStyle: boxed
    layout:
      Platform:
        style: row
        columns: 2
      Observability:
        style: row
        columns: 2
      Coming Soon:
        style: row
        columns: 2
    providers:
      openweathermap: false
    quicklaunch:
      searchDescriptions: true
      hideInternetSearch: false

  widgets.yaml: |
    - datetime:
        text_size: xl
        format:
          timeStyle: short
          dateStyle: long

    - resources:
        cpu: true
        memory: true
        disk: /
    
    - search: 
        provider: duckduckgo
        target: _blank

  proxmox.yaml: |

  kubernetes.yaml: |
    mode: cluster

  docker.yaml: |

  custom.css: |

  custom.js: |