apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default

  source:
    repoURL: https://github.com/staticparsley/homelab-nerv.git
    targetRevision: main
    path: platform/authentik/secrets
    plugin:
      name: ksops-v1.0

  destination:
    server: https://kubernetes.default.svc
    namespace: authentik

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
