apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 66.2.1
    helm:
      releaseName: kube-prometheus-stack
      values: |
        grafana:
          enabled: true
          envFromSecret: gradana-authentik-oauth
          ingress:
            enabled: true
            ingressClassName: nginx
            hosts:
              - grafana.nerv.local
            tls:
              - secretName: grafana-tls
                hosts:
                  - grafana.nerv.local
          grafana.ini:
            server:
              root_url: https://grafana.nerv.local
            auth.generic_oauth:
              enabled: true
              name: Authentik
              allow_sign_up: true
              auto_login: false
              client_id: $__env{GF_AUTH_GENERIC_OAUTH_CLIENT_ID}
              client_secret: $__env{GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET}
              scopes: openid profile email groups
              auth_url: https://authentik.nerv.local/application/o/authorize/
              token_url: https://authentik.nerv.local/application/o/token/
              api_url: https://authentik.nerv.local/application/o/userinfo/
              use_pkce: true
          
        prometheus:
          prometheusSpec:
            retention: 7d
            serviceMonitorSelectorNilUsesHelmValues: false
            serviceMonitorNamespaceSelector: {}

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true