apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sops-test
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/staticparsley/homelab-nerv.git
    targetRevision: main
    path: sandbox/sops-test
    plugin:
      name: ksops-v1.0

  destination:
    server: https://kubernetes.default.svc
    namespace: sops-test

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true