apiVersion: v1
kind: Service
metadata:
  name: quote-api
  namespace: homepage
  labels:
    app: quote-api
spec:
  type: ClusterIP
  selector:
    app: quote-api
  ports:
    - name: http
      port: 80
      targetPort: 3000
