apiVersion: v1
kind: Secret
metadata:
    name: authentik-secrets
    namespace: authentik
type: Opaque
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:huDEtz5WU1h9CiWPgh5WmT4jR21Dhkq4UljmhzHjKmBeciFwKtham5Is6K9CKJI3LLy/UOPasj2cigrQ45hyixbgW/PCOcLuLIq2j0lgles=,iv:OB0iZW3DM0Tx/dgGFPcWhQS6u2KaD8i7Uh4eSY25bEw=,tag:EdiJM8mygiiWrcnPVwT5tA==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:nXdQLcCdrhZ8NWvNPmjS565Cx5y8wRt3vMVSmKZ2fxWtzT0/XGIEQ25UKWe91bFG,iv:OXCqMHWWplHFaBc9VOrxGcYdn0iV3xQGrke02fnD1LM=,tag:lGCv4NoVN4UJrYbvmCb/Ew==,type:str]
    AUTHENTIK_BOOTSTRAP_EMAIL: ENC[AES256_GCM,data:ZXIO9pixh5a4n6+Bbiiz,iv:tQPe00cHEepbVTMEO4j3i8kdFhc8FRedWb/teB5bljc=,tag:7K2excW5RgLEROGnaOUJwA==,type:str]
    AUTHENTIK_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:BxH72jXxDCNVA9Uee8gXrzUIQuG5VGBaY3zDPsBZOvfyWrm1geLIsFhlyxYHmlO57ZoR3xzCkrKbF+XMTnU8MA==,iv:DPtY5s+BfOQAFVMNSfn2C7bojLGs9ZobYARRupG02hM=,tag:7I0NpwHjZeaO8LQY+PGhOg==,type:str]
    postgres-password: ENC[AES256_GCM,data:I+BkJB07nkHVbU6NDoxg5SPB6WWCtWhwd+6QaVscyAi1rW+t0sM+1lYvCMmwt83f,iv:vEYs4fXFC3t/MH7cKZwmyxdx8US8HPYQ57gpl+CaWPw=,tag:PIaHVsv9bDoTdfv+Y2W64Q==,type:str]
    password: ENC[AES256_GCM,data:DNbBxO2fT6SeR543uwY038BrUXlgU8Z1wE6gk0P8RBGiAdF2M996Zu/A3wMM9706,iv:dzLRFxApdreI3Yh64E0DuVijLMUkXJpYT3XTdmovODQ=,tag:gOjvKpo9nfTZumlRoN/r+Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwbHo3b1N6elYyY2Fqdith
            UTRSWE9HK2hJT0NveU9KZ3VueFFEMG1IZ1J3CmxNKzB4dVVMN2xPWWZKZGx1Mklq
            SStCd2xVd2NoZ2xQUEFjbXZDcDE0UncKLS0tIEwxTlhjVWNheTY5Z21YNzJ6enZp
            RXhxOEVLdlJLL0dESklMTGVhUGxReG8K28v9STQrco3MODW8FRMHbfgsaoz4GFIC
            dmv3e2vWazNn7m327qR3tgYziOWs59LwxlawL49ztL7V9MrndAbpBA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ytcvvrmhsu7a7kethml0m5acxxc2mhwpxrlwqdh5f4z6chny4a2q4ungyz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-15T19:08:55Z"
    mac: ENC[AES256_GCM,data:T7nK6J23FbJaaLtvWcxMFUYd4ikHZrc5erFBII5Rc8g0zBjG9y9zho7ZzPtdUS6B8kdos0zehZwciMpvvUwLp7EYrHxihZKQSfdZwlBwl3qyubkK7zdyk7XPcoDp2JI+x6338V29jPPAMehL1EAHArAZx2dTX6e/aibvqRe3yII=,iv:WndlWDnBIzVIAmcHl/9avRN80A/F+2kUA0t7qwEW8J8=,tag:NboCTuvaFoJ0mGa/49QqqA==,type:str]
    version: 3.13.2
