apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homepage-authentik-outpost
  namespace: authentik
spec:
  ingressClassName: nginx
  rules:
    - host: homepage.nerv.local
      http:
        paths:
          - path: /outpost.goauthentik.io
            pathType: Prefix
            backend:
              service:
                name: authentik-server
                port:
                  number: 80