apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: forgejo-repository-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./forgejo-repository.sops.yaml
