apiVersion: v1
kind: Secret
metadata:
    name: grafana-authentik-oauth
    namespace: monitoring
type: Opaque
stringData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:FwDtwVU9YrYWXtEw3JzOYXocZnByJGBTZKjnWvAwOLsFfApwfeT1n/4wdf0TlE/sUyc1ncdlVn0qFrXCtn7jug==,iv:NBmDHRwVVc2B6PSdXNt0dZodB8x1yGV2LPDNoXXcEzg=,tag:FDYN+sXxmMhXRjsQL0lvkw==,type:str]
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:ZkAnaNKA4+9mPgDWo9IbMozob4/lfb5JeJJQ3YDsqojh6bqZUKDrzZ71K8jEsiL4qFR1B/s5Bp1rJYqRQvlsWA==,iv:30yHuzIaDBcXGn+NsSNjAYdxFSfI/Vdctl8HybDcMz4=,tag:5rz8wql/+qMUgp6a+WkfQw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPcExtb1VxeDFlT01yMTRs
            eXIvbkM4VndiaERpZHNqWml0QUdibmp4OGg4CmYvMlpVQy9vd1RXSCtlUUJIZFdm
            RWFNT1lIQUY4R3k3YytucjNjR3U2K2cKLS0tIFphMHN5aXJrZVRWcFIyVFhwcTk3
            OGhjb21SQlRWNWVPOTRhRkRNQUd3SVUKIdiWoyWDPbz3iHAAgcBbsNciYr03B/fs
            ygBSuItbpHnaxuwyJCTqieo+b2H1gzkDaczUs44qy81a2llVc+Q2CA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ytcvvrmhsu7a7kethml0m5acxxc2mhwpxrlwqdh5f4z6chny4a2q4ungyz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-15T20:55:27Z"
    mac: ENC[AES256_GCM,data:bYlF037czW931sjRLd7aqbTw7a+rd6YzdXO5CklqOIk5tkypD7krVeB25UyDEqPch5yfhde6yt3Ppz0aBIgh4fi9fhlY//igOMeBZsZhktdCE9GLX+4cYSse3/DBA1unTn0Tz9VvVanx0smt7zKHek+iRRgJb3aPoGuPDzCDx34=,iv:XGeg64VomzgBaJ9Utu9bPcBXzxmWnW9wtN+wG10CPvM=,tag:hAJrfPmAYUwdq+CBsK9PzQ==,type:str]
    version: 3.13.2
