apiVersion: v1
kind: Secret
metadata:
    name: grafana-authentik-oauth
    namespace: monitoring
type: Opaque
stringData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:FwDtwVU9YrYWXtEw3JzOYXocZnByJGBTZKjnWvAwOLsFfApwfeT1n/4wdf0TlE/sUyc1ncdlVn0qFrXCtn7jug==,iv:NBmDHRwVVc2B6PSdXNt0dZodB8x1yGV2LPDNoXXcEzg=,tag:FDYN+sXxmMhXRjsQL0lvkw==,type:str]
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:Dg8SURMKCWpaUyOwe+YjfK9Sq5Sg+9grLHQQ/2R8QIt5H/0RKju5WKSahdU6n2RLicwCBPlLHWHxymXNWKbIqt+T0bNWMLLI6FR7Bw+J1/WcVg5kGDIJXcZcJw0cLkmSCu5XHuSiqeGOj4NTY1+b07q9cqQ+VGVxn+1Z78t9p7M=,iv:95wEKfGe3UWgZ6y9BA6oijtz8iw8EMI6PcO0FTiNM0Q=,tag:3X/oX8qDEDEl+VLPxphmVg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPcExtb1VxeDFlT01yMTRs
            eXIvbkM4VndiaERpZHNqWml0QUdibmp4OGg4CmYvMlpVQy9vd1RXSCtlUUJIZFdm
            RWFNT1lIQUY4R3k3YytucjNjR3U2K2cKLS0tIFphMHN5aXJrZVRWcFIyVFhwcTk3
            OGhjb21SQlRWNWVPOTRhRkRNQUd3SVUKIdiWoyWDPbz3iHAAgcBbsNciYr03B/fs
            ygBSuItbpHnaxuwyJCTqieo+b2H1gzkDaczUs44qy81a2llVc+Q2CA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ytcvvrmhsu7a7kethml0m5acxxc2mhwpxrlwqdh5f4z6chny4a2q4ungyz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-15T21:05:15Z"
    mac: ENC[AES256_GCM,data:jY93uqoXVNtBzkGmYGm7fRdzPvnTppoS2Lgri63oSZWU0Z4YZ+Q6rvrKVsL2iS6F+M4ShcIhqF2v64CIagcx77fT10T1WAYuM/CqH7Qk5xwc3e+PlMeSnkR1TBZgI2YhPU2zg9PK+mWidgP2P75QE5CSDFTBmHVWOPHoUMVlpfk=,iv:cQKDYtwUH7WudnQLUQEA737bKIAHZRRy2tMoO4BQWvQ=,tag:JJ0X2vNeQUQlT36SR5DfqA==,type:str]
    version: 3.13.2
