apiVersion: v1
kind: Secret
metadata:
    name: grafana-authentik-oauth
    namespace: monitoring
type: Opaque
stringData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:phuGXf1QUxn2/ViufS3mdeBJunjuOBtsYhwSd13rTx3uXT0Xtea/Qw==,iv:D0At22WtjIQZ/t7Hj82KqhsGBz14gYrDJcYGaGg8bB8=,tag:UfAjbD/Ow4nDEr5naXRGPg==,type:str]
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:sh0NHuBr+t+rV1XgiNqYNBd52d6e5WSAChKiI6pBVdY9iKaTbRDaRQ==,iv:BVBl50l+HkFtVqMaYLTgWTtQ2u+D49vc0Bi2lwAcl8Q=,tag:CTh8w9R9PKHjxTePMPTITg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPcExtb1VxeDFlT01yMTRs
            eXIvbkM4VndiaERpZHNqWml0QUdibmp4OGg4CmYvMlpVQy9vd1RXSCtlUUJIZFdm
            RWFNT1lIQUY4R3k3YytucjNjR3U2K2cKLS0tIFphMHN5aXJrZVRWcFIyVFhwcTk3
            OGhjb21SQlRWNWVPOTRhRkRNQUd3SVUKIdiWoyWDPbz3iHAAgcBbsNciYr03B/fs
            ygBSuItbpHnaxuwyJCTqieo+b2H1gzkDaczUs44qy81a2llVc+Q2CA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ytcvvrmhsu7a7kethml0m5acxxc2mhwpxrlwqdh5f4z6chny4a2q4ungyz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-15T20:08:30Z"
    mac: ENC[AES256_GCM,data:hP2fqz7MXPCCZeCy3A1fMfFiv4S5P3/tH9IhVMaDdLFmD8VMsXzNRI6zqp+D9KWW/Gr+7N2EchJ9QmilL35MZp3/m0QorrHurJc5tZEvyjigSLaIMj09jKTgZL7WQZw4Phvmp6SuLCD1ePc9C7ae6RhSLJMpSrIRTI7bBY1KRdg=,iv:mVLfa3HlL+mHL5TjAMgaAqqBP+cfWSnbhQxJKeiUMp4=,tag:p27ciWUBbQooknLtmY/FKQ==,type:str]
    version: 3.13.2
