apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: grafana-oauth-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./grafana-oauth.sops.yaml
