apiVersion: v1
kind: Secret
metadata:
    name: sops-test-secret
    namespace: sops-test
type: Opaque
stringData:
    test-value: ENC[AES256_GCM,data:/RubM+FwZXRK2lvCqYQDnqy8dNgpbJQ=,iv:h1u9L63vRynOMsv/QNnRIVFgYU048Ov7rhgJsHzTN4o=,tag:U29P03AxMGbL5OBy8DROgg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDZVlua1lrRVcybmhhVGpV
            aWRWMXBJczQ0OTZSTlNzMmc2dmpPeU1YL2pRCjVOOHZpUTJGYnlKZEhQcHdmYmph
            RjV4TTJCVmNhUThBZkxkeG44Nnp3cFkKLS0tIHd3YkZLYWlCd2tZeDhkM0NhSUVk
            UFZzblhLMElOMy9BOHFzQUlMbk5FRUkKfqBa0bhJxUANoUUI8R1jbs7AGWZom/Wr
            saXhzr6FiGgyadlT1RDjtlqcSw4+aPMPq5Qxk0+SaeCCpjnRI9x1UQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ytcvvrmhsu7a7kethml0m5acxxc2mhwpxrlwqdh5f4z6chny4a2q4ungyz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-15T18:45:32Z"
    mac: ENC[AES256_GCM,data:AHvYZR35sUmo+lJgDYxNoJO8G9rkVfhcSi9Vez+f967TQjIEaWqDzdZfPBRfiXIsrEKDaCdtq2dYBIXuvCGZpnLnZ8kGxAyygEff/HfHmlWCvtpzHiCKSuMKejs8pMRo9Cggh/D+uFNByd7Q/PA8qqOk3Vu85Bw09f5b+NxXwCg=,iv:vgp5EhJm4IkR3KLtLTlzI5di3jFGxdmAb9d5M3Ib1Fs=,tag:7DdX5oqs3aCN63ynlyc96Q==,type:str]
    version: 3.13.2
