apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v3.4.4/manifests/install.yaml
  - cmp-ksops.yaml

patches:
  - path: repo-server-ksops-patch.yaml 
  
  - target:
      version: v1
      kind: ConfigMap
      name: argocd-cmd-params-cm
    patch: |-
      $patch: delete
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: argocd-cmd-params-cm